#!/bin/bash

# Define color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

handle_error() {
    echo -e "${RED}Error: $1${NC}"
    exit 1
}

success_msg() {
    echo -e "${GREEN}$1${NC}"
}

info_msg() {
    echo -e "${BLUE}$1${NC}"
}

warning_msg() {
    echo -e "${YELLOW}$1${NC}"
}

# Ensure the script is run as root
if [[ $EUID -ne 0 ]]; then
    handle_error "This script must be run as root. Please run with 'sudo'."
fi

# Get the actual user who invoked sudo
ACTUAL_USER=$(logname || who am i | awk '{print $1}')
ACTUAL_HOME=$(eval echo ~${ACTUAL_USER})

# Check if required files exist
MONITORS_XML="./data/monitors.xml"
if [[ ! -f "$MONITORS_XML" ]]; then
    handle_error "monitors.xml file not found in ./data/"
fi

echo "Current directory: $(pwd)"
echo "Listing ./data/:"
ls -l ./data/

info_msg "_________INSTALL REQUIRED DEPENDENCIES_________"

# Install Nvidia drivers
apt install -y nvidia-driver || handle_error "Failed to install nvidia-drivers"

# Set file permissions and move the monitors.xml file
chmod 644 "$MONITORS_XML" || handle_error "Failed to set permissions on monitors.xml"

# Remove existing monitors.xml files if they exist
[[ -f "/var/lib/gdm3/.config/monitors.xml" ]] && rm -f "/var/lib/gdm3/.config/monitors.xml"
[[ -f "${ACTUAL_HOME}/.config/monitors.xml" ]] && rm -f "${ACTUAL_HOME}/.config/monitors.xml"

# Ensure the target directories exist
mkdir -p "/var/lib/gdm3/.config/"
mkdir -p "${ACTUAL_HOME}/.config/"

# Define the xorg.conf content to be written
XORG_CONF_CONTENT=$(
    cat <<'EOF'
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 550.120

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "HP"
    ModelName      "Compaq LE911"
    HorizSync      30-82
    VertRefresh    56-76
    Option         "DPMS"
    # Add modeline for 1280x1024
    Modeline "1280x1024_60.00" 109.00 1280 1368 1496 1712 1024 1027 1034 1063 -hsync +vsync
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    Option         "ModeValidation" "NoEdidMaxPClkCheck,NoMaxSizeCheck,NoMaxPClkCheck,NoHorizSyncCheck,NoVertRefreshCheck"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
        Modes      "1280x1024_60.00" "1280x1024" "1024x768" "800x600"
    EndSubSection
EndSection
EOF
)

# Path to the xorg.conf file
XORG_CONF_PATH="/etc/X11/xorg.conf"

# Backup the existing xorg.conf file (if it exists)
if [ -f "$XORG_CONF_PATH" ]; then
    echo "Backing up the existing xorg.conf to xorg.conf.bak"
    cp "$XORG_CONF_PATH" "${XORG_CONF_PATH}.bak"
fi

# Write the new xorg.conf content
echo "$XORG_CONF_CONTENT" >"$XORG_CONF_PATH"

# Set appropriate permissions for the new xorg.conf file
chmod 644 "$XORG_CONF_PATH"

echo "NVIDIA display settings have been applied. Please restart your X server or reboot the system for changes to take effect."

# Move the new monitors.xml file to the appropriate locations
echo "Moving monitors.xml from $MONITORS_XML to /var/lib/gdm3/.config/"
cp "$MONITORS_XML" "/var/lib/gdm3/.config/" || handle_error "Failed to move monitors.xml to /var/lib/gdm3/.config/"
echo "Moving monitors.xml to ${ACTUAL_HOME}/.config/"
cp "$MONITORS_XML" "${ACTUAL_HOME}/.config/" || handle_error "Failed to move monitors.xml to ${ACTUAL_HOME}/.config/"

success_msg "Nvidia drivers installed and monitors.xml moved successfully."
